name: blinkit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
   - family: bold
     fonts:
       - asset: assets/fonts/Poppins-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
   - family: regular
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700